survey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('surveys.urls')),
    path('user', include('users.urls')),
]

surveys/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:survey_id>/', views.detail, name='detail')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = {

}

surveys/models.py
from django.db import models
from django.utils import timezone
from users.models import User


# Create your models here.
class Survey(models.Model):
    survey_name = models.CharField(max_length=200)
    description = models.TextField()
    added_time = models.TimeField(auto_now_add=timezone.now())
    published_time = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.survey_name


class Question(models.Model):
    survey = models.ForeignKey('Survey', on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

users/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    nickname = models.CharField(max_length=30, unique=True)
    age = models.IntegerField()

    class Sex(models.TextChoices):
        MALE = 'ML'
        FEMALE = 'FM'
        UNDECIDED = 'UD'

    sex = models.CharField(max_length=2, choices=Sex.choices, default=Sex.UNDECIDED)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

surveys/views.py
from django.shortcuts import render, HttpResponse
from .models import Survey, Question, Choice


# Create your views here.
def index(request):
    surveys = Survey.objects.all()
    return render(request, 'surveys/index.html', context={'surveys': surveys})


def detail(request, survey_id):
    survey = Survey.objects.get(pk=survey_id)
    return render(request, 'surveys/detail.html', context={'survey': survey})

users/views.py
from django.shortcuts import render

# Create your views here.

surveys/templates/surveys/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>survey.survey_name</title>
</head>
<body>
    {% if survey %}
        {% for question in survey.question_set.all %}
            <h2>{{ question }}</h2>
            {% for choice in question.choice_set.all %}

                    <input type="radio" id="radioButton">{{ choice }} <br>

            {% endfor %}
        {% endfor %}
    {% endif %}
</body>
</html>

surveys/templates/surveys/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Surveys</title>
</head>
<body>
    {% if surveys %}
        {% for survey in surveys %}
             <a href="{% url 'detail' survey.id %}"><h1>{{ survey }}</h1></a>
        {% endfor %}

    {% endif %}
</body>
</html>